### ISSUE TITLE
Error when usb drive is not connected [Investigation]

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-export#13]
## Description

When `sd-export-usb` is shutdown and there is no usb drive plugged in, `qvm-open-in-vm` as well as `qvm-start` fails with Qubes pop notification: `Domain sd-export-usb has failed to start: usb device sys-usb:2-2 not available`

The exception the client gets back from subprocess.check_call is: `subprocess.CalledProcessError('ERROR: Command 'qvm-open-in-vm sd-export-usb /tmp/tmp3n23ok9j/usb-test.sd-export' returned non-zero exit status 126'`. This is a generic "command cannot be executed" error, which seems too generic to interpret as "the usb drive is not plugged in so the vm cannot start".

For now, I'm making it so the client tells the user to try plugging in their usb drive when there is a generic "command cannot be executed" exception.

## Steps to reproduce

1. unplug the usb drive and shutdown `sd-export-usb`
2. run `qvm-start sd-export-usb`

**Expected**
For the vm to start. When it needs to access the usb drive and it's not there, then I would expect to see `USB_NOT_CONNECTED`.

**Actual**
The vm does not start and the client can only get back a generic exception.

**Comment by redshiftzero** [comment]
after @rmol's change in https://github.com/freedomofpress/securedrop-workstation/pull/323, this one should no longer be relevant. let me know if you disagree @creviera!

**Comment by creviera** [comment]
agreed :+1:
