### ISSUE TITLE
Printer preflight checks

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-export#23]
#### Description
Until we decouple export from the client, the client will handle errors and wait until it knows there is a single printer attached before sending a document over to the Export VM to be printed.  

Our design is to show a `Preparing to print` message in the client while the Export VM does the following:

* boots up (it might have been manually shutdown) 
* returns `PRINTER_NOT_FOUND` if the printer cannot be found and or `MULTIPLE_PRINTERS_FOUND` if multiple printers are found

Also this issue needs to [update this code](https://github.com/freedomofpress/securedrop-export/blob/78bcbfe6d26f5456f68cdd7c7b30353eaa7bb4a1/securedrop_export/export.py#L300-L313) so that we don't always assume that the first printer result from `lpinfo -v` is the one we want. Instead it should also return `MULTIPLE_PRINTERS_FOUND` if there is more than one result.

**Comment by creviera** [comment]
Resolves https://github.com/freedomofpress/securedrop-client/issues/632

**Comment by redshiftzero** [comment]
closed in #48
