### ISSUE TITLE
Add status code for multiple attached devices 

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-export#25]
## Description

Return `MULTIPLE_DRIVES_CONNECTED` status code when multiple luks-encrypted devices are attached (handle printer separately since printer support is still in the works).

See https://github.com/freedomofpress/securedrop-export/issues/21#issue-514291961 for more details, but this issue is just to add the status code so we can inform the user to detach other devices.

**Comment by gonzalo-bulnes** [comment]
Will be done in #105 :slightly_smiling_face: 

@rocodes I let you add the corresponding `Fixes #25` if you think it makes sense!
