### ISSUE TITLE
Add support for different device names

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-export#26]
## Description

Add support for devices other than `/dev/sda` and `/dev/sda1`.

Right now, an export operation will fail if a user unplugs a device and plugs it back in before we luksClose, because it'll come back with a different name, like `/dev/sdb`.

**Comment by creviera** [comment]
## more info

* a device name of `sda` is not guaranteed if the device is yanked out during an export and reattached because it might be reattached as `sdb` if the export script was unable to properly luks-close and unmount the drive.

* depending on the hardware some devices will show up as `xvdX` devices instead of `sdX` devices, where `X` is the number indicating order of unique devices attached (see https://askubuntu.com/a/166087)

right now, the workaround is to attach the device commandline from dom0

**Comment by redshiftzero** [comment]
@harlo had an interesting qubes observation which is that if you attach the USB via the CLI the device name is /dev/sd* and if you attach via the GUI it's /dev/xvd* (I checked and I see the same) 

To @creviera's point, we should allow drives named both /dev/xvd* and  /dev/sd* - we keep track of a list of possible device names, iterate through them, if we find one that works (i.e. is luks encrypted) we try to use it, if we find multiple then #25?

**Comment by creviera** [comment]
just a quick note....

until this issue is implemented, there are two workarounds (for people giving demos and developing export):

1.
> right now, the workaround is to attach the device commandline from dom0

2.
if you want to use the guid, use the bottom menu (red) to attach your device instead of the top menu (blue)

![device types](https://user-images.githubusercontent.com/4522213/69384670-c427c580-0c71-11ea-80c0-6f6bc60e2981.png)
