### ISSUE TITLE
Make SDExport.exit_gracefully more standalone

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-export#44]
Followup from #41 (see [comment here](https://github.com/freedomofpress/securedrop-export/pull/41#pullrequestreview-334242539))

I'm not sure how to best do this, but when I was working on #41, I was wondering if we can make `SDExport.exit_gracefully` more standalone to decouple more code from `SDExport`. It would be nice to extract that method into a utility function since it's used almost everywhere. The challenge is that part of its cleanup is (if it exists) it's removing a submission's `tmpdir`. We'd either need to pass the `tmpdir` around everywhere, which is messy, or just leave it as a method on `SDExport`, or do something else. If anyone has any ideas on how to nicely refactor this, get loud.

**Comment by rmol** [comment]
How about:
- dispensing with `exit_gracefully` and just letting exceptions bubble
- adding `tmpdir` to `SDExport.__init__` arguments
- in `entrypoint.start`, using `with tempfile.TemporaryDirectory() as tmpdirname:` around construction/usage of `SDExport`, and catching any exceptions in one finally block where we ensure we print something and exit 0

It would mean some tedious refactoring of the `exit_gracefully` calls to raise exceptions from `ExportStatus` messages.
