### ISSUE TITLE
ppdc Warning - overlapping filename

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-export#51]
# STR
1. Open the client and click on "Print" next to a document after attaching your USB printer to the sd-devices VM

# Expected

Print is successful

# Actual

The client  displays a `ppdc Warning - overlapping filename <blah.ppd>`. If it doesn't do it the first time, it should do it the second time you request to print.

**Comment by eloquence** [comment]
(Encountered again during 0.5.0 QA)

**Comment by creviera** [comment]
(Encountered again during pilot usage today)

**Comment by eaon** [comment]
I can confirm this - it happens consistently every time `ppdc` is run with `hpcups.drv`, which in our case is every time `sd-devices` is started and the printer is used for the first time in that session. Despite emitting that warning, `ppdc`'s return code is still 0 though, and the printer works normally afterwards.

I think it's safe to ignore warnings like these and continue to the printing dialog
