### ISSUE TITLE
Improve error handling for unsupported drive configurations

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-export#70]
Informational finding `TOB-SDW-023` from the [2020 SecureDrop Workstation audit (PDF)](https://media.securedrop.org/media/documents/Trail_of_Bits_SecureDrop_Workstation_Audit_2020.pdf) notes that:
>When the export feature is used with a pendrive with unsupported configurations, the errors returned to the user are not describing the issues appropriately. This may lead to users believing their pendrives are broken or wasting time on finding out what's the correct cause of the issue.
>
> One case of this is when a pendrive has multiple partitions, in such a case, an `USB_ENCRYPTION_NOT_SUPPORTED` error is returned. Another case is when there no filesystem was created after creating a LUKS partition on the
usb drive. (...)
>
> And last, the `unlock_luks_volume` code path is also problematic. A pendrive with the DISK (`/dev/sdb`) and the PARTITION (`/dev/sdb1`, or, not existing) is encrypted, it seems that the `luks_header = subprocess.check_output(["sudo", "cryptsetup", "luksDump", self.device])` may contain an UUID line, but the device may not be already unlocked. In such a case, the later mount attempt fails with a similar error as shown in Figure 23.2. 

The report recommends improving error handling and in the long term, potentially supporting more configurations of USB drives.

## Scenarios

See https://github.com/freedomofpress/securedrop-export/issues/70#issuecomment-1340371511

**Comment by gonzalo-bulnes** [comment]
@rocodes I think we're addressing some of this as part of #105 and the related **securedrop-client** work. Let's do a checklist run to confirm? Now that we're expanding the device API may be a good time, what do you think?

**Comment by rocodes** [comment]
In terms of resolving this issue on the export side specifically (as opposed to the client-side), in my opinion this issue will be resolved with #105, even if the changes aren't yet user-visible.

The changes add support for the following relevant error codes to be passed to the client ([link](https://github.com/freedomofpress/securedrop-export/pull/105/files#diff-dcfd23a386fcec623e1f72b7b69ed2c760d6996f945eb95bd1300989bba4942b)):

-  `MULTI_DEVICE_DETECTED` (2 USBs at once) and `INVALID_DEVICE_DETECTED` (mis-partitioned) replace USB_ENCRYPTION_NOT_SUPPORTED and add differentiation for those kinds of issues at the block device level.
 
 - `ERROR_MOUNT` responds to filesystem-and mounting-related issues once the device is unlocked.

- Nested LUKS containers are not something we need to support or worry about IMO.
 
Regarding the second issue, the codepath for mounting luks drives, I believe it is also resolved by this refactor.
`cryptsetup luksDump` is still used to grab the LUKS UUID, but before every stage where the device will be operated on, we test to see if the device is mapped or not (i.e. unlocked or not), and mounted or not.

**Comment by gonzalo-bulnes** [comment]
@rocodes Considering that this issue is open against the export repo, I think you're actually right in calling out for it to be closed by #105 independently of GUI support. That somehow slipped my mind 👍

On the rest I think we're already in agreement.

**Comment by gonzalo-bulnes** [comment]
Merging as agreed now that #105 is merged.
