### ISSUE TITLE
Not seeing ERROR_USB_CONFIGURATION as expected

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-export#8]
## Description

We communicate from `sd-svs` to `sd-export-usb` via archive files that specify "devices" to indicate whether or not we want to export a file to a printer device to be printed or a usb drive. 

The current design expects this ordering of operations for exporting a file to a usb drive:

1. send an archive with device=`usb-test` (to verify that  `sd-export-usb` is set up properly as well as if a usb device is attached)
2. send an archive with device= `usb-disk` (to verify that the attached usb drive is luks-encrypted)
3. send an archive with device=`disk` (to export the file(s) to the attached usb drive)

When `sd-export-usb` is misconfigured, I am not seeing `ERROR_USB_CONFIGURATION` as expected.

## STR

1. reboot your machine, plug in a couple devices, use a usb 2.0 device, or wait until after an qubes-dom0-update (the exact steps to reproduce are still being worked out here https://github.com/freedomofpress/securedrop-workstation/issues/307 so try one or a combination of these things)
2. send `qvm-open-in-vm sd-export-usb archive.sd-export` once for all three scenarios where device is set to `usb-test`, `usb-disk`, and `disk` and the archive is set up according to specification.

**EXPECTED**
I would expect the client to receive `ERROR_USB_CONFIGURATION` no matter what "device" is set to when communicating from sd-svs to sd-export-usb. 

**ACTUAL**
The actual behavior is:
  *  `sd-export-usb` copies over the archive to a temp directory and returns `ERROR_GENERIC` when device is set to `disk`
  * `sd-export-usb` returns `USB_CONNECTED` when sd-export-usb is running, regardless of whether or not the usb device is plugged in, when device is set to `usb-test`
  * `sd-export-usb` returns `USB_NO_SUPPORTED_ENCRYPTION` when device is set to `disk-test`

## Background 

The PCI bus ID gets reassigned sometmies (e.g. `usb:4-2` with a PCI bus ID of 4 and a USB device ID of 2 gets reassigned to `usb:1-2`) and `sd-export-usb` can no longer access the usb drive connected to that port, see https://github.com/freedomofpress/securedrop-workstation/issues/307 to learn more. We need to make sure we get the proper `ERROR_USB_CONFIGURATION` if this change occurs.

**Comment by emkll** [comment]
This issue should be resolved/no longer occur, based on the changes recently introduced in https://github.com/freedomofpress/securedrop-workstation/pull/324  (automatic attachment to sd-devices, formerly known as sd-export-usb).
