### ISSUE TITLE
Remove copy of metadata.json in sd-devices after export

### ISSUE THREAD

**Issue by creviera** [freedomofpress/securedrop-export#9]
## Description

The submissions and metadata files (containing plaintext user passwords) are being stored on `sd-export-usb`. It should be automatically deleted after an export operation or not written to disk at all.

**Comment by creviera** [comment]
Might want to also consider separating passwords from the export archive files, so that passwords don't have to be stored on disk at all. 

(As far as the export files go, I think the future plan is to eventually pass these files in encrypted form.)

**Comment by redshiftzero** [comment]
I was checking on this just now and currently for `DiskExportAction` (in the `copy_submission` method) we are cleaning up the submission files themselves. We do keep `metadata.json` around though (albeit in `/tmp`), which we should clean up.

**Comment by eloquence** [comment]
(Retitled issue to clarify scope. Noting for the record that `sd-devices` is disposable for Qubes session length so removal is ensured both via `tmpfs` usage and Qubes session termination.)

**Comment by creviera** [comment]
Even though sd-devices is disposable, it's long-lived, so just want to bump this for nomination.

**Comment by eloquence** [comment]
(We didn't discuss this today, will touch base on this at standup tomorrow.)

**Comment by gonzalo-bulnes** [comment]
@rocodes Because we just talked about post-export cleanup. Do you have in mind if the `metadata.json` file is still kept around once export is done?

If so, this looks like it could become a [good first issue][gfi] once #105 is done?

  [gfi]: https://github.com/freedomofpress/securedrop/wiki/Good-first-issues

**Comment by rocodes** [comment]
It makes sense to remove it after export. If it doesn't fit into #105 it's definitely a good first issue.
